databases:
  - name: authenticate-me
    databaseName: authenticate-me
    user: authenticate-me

services:
  - type: web
    name: authenticate-me
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authenticate-me
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false